### ISSUE TITLE
IsCreditCardNumberValid returns invalid value

### ISSUE THREAD

**Issue by kakarotto67** [natalicat/NumberCreditCard#1]
Please change method IsCreditCardNumberValid so it will return **true** if card number is valid, otherwise - **false**.

**Comment by natalicat** [comment]
Done

**Comment by natalicat** [comment]
Зробила.

> Суббота,  7 мая 2016, 15:49 +03:00 от Roman notifications@github.com:
> 
> Please change method IsCreditCardNumberValid so it will return  true if card number is valid, otherwise -  false .
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or  view it on GitHub

## 

Natali UK

**Comment by kakarotto67** [comment]
IsCreditCardNumberValid still returns **string**...
