### ISSUE TITLE
Next card number is generated when it shouldn't

### ISSUE THREAD

**Issue by kakarotto67** [natalicat/NumberCreditCard#2]
Pass "4999999999999999993" (VISA) into your GenerateNextCreditCardNumber method
Expected result: some message as no more VISA's numbers left
Actual result: "5000000000000000005" is returned (it is valid, but this is not VISA vendor)

**Comment by natalicat** [comment]
resolved

**Comment by intrueder** [comment]
Still reproducable

**Comment by natalicat** [comment]
"Нових номерів кредитної картки для вендора VISA немає!"
fixed
