### ISSUE TITLE
GetCreditCardVendor returns incorrect vendor

### ISSUE THREAD

**Issue by kakarotto67** [natalicat/NumberCreditCard#5]
Pass "50000000000006114" into your GetCreditCardVendor method
Expected result: Unknown as this number isn't valid
Actual result: Maestro (just pass this number into your IsCreditCardNumberValid method and you will see that it will return false)

**Comment by kakarotto67** [comment]
The same issue with "41111111111111112" and "3434343434343433".

**Comment by natalicat** [comment]
resolved

**Comment by natalicat** [comment]
Усунула зауваження.

> Суббота,  7 мая 2016, 16:18 +03:00 от Roman notifications@github.com:
> 
> The same issue with "41111111111111112" and "3434343434343433".
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or  view it on GitHub

## 

Natali UK
